spring:
  application:
    name: k-market-navigator-backend
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
